apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-1wjb
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0024-tenant/tkrw-pr712-0075-0024-app/devfile-sample-1wjb@sha256:9766b7b6f68a229fb27f717aff132c6e51bda5350041b6bf2c3e3777b1eda009
        name: my-nodejs
        resources: {}
status: {}
